language: go
go:
  - 1.9.x
  - 1.10.x
install:
  # Fetch dependencies
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - mv dep /usr/local/bin/dep
script:
  - ./configure
  # Run tests
  - make test
sudo: false
notifications:
  email: false
