language: go
go:
  - 1.10.x
  - 1.11.x
before_install:
  - sudo apt-get install -y qemu-user-static
  - sudo docker run --rm --privileged multiarch/qemu-user-static:register
install:
  # Fetch dependencies
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep
  - mv dep $GOPATH/bin/dep
script:
  - ./configure
  # Run tests
  - make test
sudo: false
notifications:
  email: false
